# Generated by Django 3.0.4 on 2020-03-16 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='writer',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.CharField(default='-', max_length=12),
        ),
        migrations.AlterField(
            model_name='news',
            name='name',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AlterField(
            model_name='news',
            name='pic',
            field=models.TextField(),
        ),
    ]
