# Generated by Django 3.0.4 on 2020-04-14 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20200317_1733'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='pic',
            new_name='picurl',
        ),
        migrations.AddField(
            model_name='news',
            name='picname',
            field=models.TextField(default='-'),
        ),
    ]
