# Generated by Django 3.0.4 on 2020-04-16 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20200416_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='body_text',
            field=models.TextField(default='-'),
        ),
        migrations.AlterField(
            model_name='news',
            name='short_text',
            field=models.TextField(default='-'),
        ),
    ]
