# Generated by Django 3.0.4 on 2020-04-16 13:49

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_auto_20200416_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='short_text',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
