# Generated by Django 3.0.4 on 2020-04-16 15:02

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_auto_20200416_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='body_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank='True', null='True'),
        ),
        migrations.AlterField(
            model_name='news',
            name='short_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank='True', null='True'),
        ),
    ]
