# Generated by Django 3.0.4 on 2020-04-16 16:53

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_auto_20200416_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='body_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='news',
            name='picname',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='news',
            name='short_text',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
