# Generated by Django 3.0.4 on 2020-04-16 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0015_auto_20200417_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='picname',
            field=models.ImageField(default='-', upload_to=''),
        ),
    ]
