# Generated by Django 3.0.4 on 2020-05-16 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0020_news_trending'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='trending',
            field=models.BooleanField(),
        ),
    ]
