# Generated by Django 3.0.4 on 2020-05-17 06:22

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0022_auto_20200516_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='intro_text',
            field=ckeditor.fields.RichTextField(default='-'),
        ),
    ]
