# Generated by Django 3.0.4 on 2020-05-17 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0023_news_intro_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='identifier_home',
            field=models.CharField(default='-', max_length=25),
        ),
    ]
