# Generated by Django 3.0.4 on 2020-06-06 11:13

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0025_auto_20200606_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='body_text',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
