# Generated by Django 3.0.4 on 2020-06-06 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0026_auto_20200606_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='intro_text',
            field=models.TextField(),
        ),
    ]
