# Generated by Django 3.0.4 on 2020-07-06 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0028_auto_20200607_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='name',
            field=models.CharField(default='-', max_length=100),
        ),
    ]
