# Generated by Django 3.0.4 on 2020-07-07 05:12

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0029_auto_20200706_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='body_text',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
