# Generated by Django 3.0.4 on 2020-07-07 05:22

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0030_auto_20200707_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='body_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
