# Generated by Django 3.0.4 on 2020-07-12 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0033_auto_20200708_1923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='identifier_home',
        ),
        migrations.RemoveField(
            model_name='news',
            name='trending',
        ),
        migrations.RemoveField(
            model_name='news',
            name='views',
        ),
    ]
