# Generated by Django 3.0.4 on 2020-07-15 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0036_auto_20200715_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='piccredit',
            field=models.TextField(blank=True, null=True),
        ),
    ]
