# Generated by Django 3.0.4 on 2020-06-24 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(default='-')),
                ('name', models.CharField(default='-', max_length=50)),
                ('email', models.CharField(default='-', max_length=50)),
            ],
        ),
    ]
