# Generated by Django 3.0.4 on 2020-06-24 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments_Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_body', models.TextField(default='-')),
                ('reply_name', models.CharField(default='-', max_length=50)),
                ('reply_email', models.CharField(default='-', max_length=50)),
                ('news_id', models.IntegerField(default=0)),
                ('main_comment_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='comments',
            name='news_id',
            field=models.IntegerField(default=0),
        ),
    ]
