# Generated by Django 3.0.4 on 2020-06-25 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_auto_20200625_0227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='news_id',
        ),
    ]
