# Generated by Django 3.0.4 on 2020-06-25 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_auto_20200625_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='news_id',
            field=models.IntegerField(default=0),
        ),
    ]
