# Generated by Django 3.0.4 on 2020-06-26 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0005_comments_news_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments_reply',
            old_name='main_comment_id',
            new_name='comment_id',
        ),
    ]
