# Generated by Django 3.0.4 on 2020-06-26 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0006_auto_20200626_1234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments_reply',
            old_name='reply_body',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='comments_reply',
            old_name='reply_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='comments_reply',
            old_name='reply_name',
            new_name='name',
        ),
    ]
