# Generated by Django 3.0.4 on 2020-07-01 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0007_auto_20200626_1241'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments_doodle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments_custom_picname', models.CharField(default='-', max_length=50)),
                ('comments_picurl', models.TextField(default='-')),
                ('comments_picname', models.TextField(default='-')),
            ],
        ),
    ]
