# Generated by Django 3.0.4 on 2020-07-01 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0008_comments_doodle'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
