# Generated by Django 3.0.4 on 2020-05-20 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('singular_manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Identifier',
            new_name='Singular_Manager',
        ),
    ]
