# Generated by Django 3.0.4 on 2020-05-27 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('singular_manager', '0003_auto_20200520_1346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='singular_manager',
            old_name='identifier',
            new_name='identifier_home',
        ),
    ]
