# Generated by Django 3.0.4 on 2020-03-16 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200316_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='settings',
            field=models.TextField(default='-'),
        ),
    ]
