# Generated by Django 3.0.4 on 2020-03-16 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_main_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='fb',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AlterField(
            model_name='main',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='main',
            name='settings',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AlterField(
            model_name='main',
            name='tw',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AlterField(
            model_name='main',
            name='yt',
            field=models.CharField(default='-', max_length=50),
        ),
    ]
