# Generated by Django 3.0.4 on 2020-03-16 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200316_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='cell',
            field=models.CharField(default='-', max_length=15),
        ),
    ]
