# Generated by Django 3.0.4 on 2020-05-16 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_main_cell'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='trending',
            field=models.TextField(default='-'),
        ),
    ]
