# Generated by Django 3.0.4 on 2020-05-16 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_main_trending'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='main',
            name='trending',
        ),
    ]
