# Generated by Django 3.0.4 on 2020-07-08 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20200708_1923'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FeaturedHome',
            new_name='MostPopular',
        ),
    ]
