# Generated by Django 3.0.4 on 2020-07-08 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20200708_1932'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasonryHome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catname', models.CharField(default='-', max_length=50)),
                ('name', models.CharField(default='-', max_length=100)),
                ('picurl', models.TextField(default='-')),
                ('date', models.CharField(default='-', max_length=50)),
                ('position', models.CharField(default='-', max_length=50)),
                ('intro_text', models.TextField()),
            ],
        ),
    ]
