# Generated by Django 3.0.4 on 2020-07-10 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_masonryhome'),
    ]

    operations = [
        migrations.CreateModel(
            name='PicturesGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('givenname', models.CharField(default='-', max_length=100)),
                ('picname', models.CharField(default='-', max_length=100)),
                ('picurl', models.CharField(default='-', max_length=100)),
            ],
        ),
    ]
