# Generated by Django 3.0.4 on 2020-07-10 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_picturesgallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraPages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagename', models.CharField(default='-', max_length=100)),
                ('pageurl', models.CharField(default='-', max_length=100)),
            ],
        ),
    ]
