# Generated by Django 3.0.4 on 2020-07-10 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_extrapages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extrapages',
            name='pageurl',
        ),
    ]
