# Generated by Django 3.0.4 on 2020-07-10 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_remove_extrapages_pageurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='extrapages',
            name='pagecontent',
            field=models.CharField(default='-', max_length=100),
        ),
    ]
