# Generated by Django 3.0.4 on 2020-07-10 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_extrapages_pagecontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrapages',
            name='pagecontent',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
