# Generated by Django 3.0.4 on 2020-07-12 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_trending'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrapages',
            name='pagecontent',
            field=models.TextField(blank=True, null=True),
        ),
    ]
