# Generated by Django 3.0.4 on 2020-06-27 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_manager_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manager',
            old_name='utxt',
            new_name='username',
        ),
    ]
